version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - release
jobs:
  test:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

      # run code coverage
      - run:
          name: Code coverage report
          command: yarn coverage

      - run:
          name: Upload code coverage report
          command: ./node_modules/codecov/bin/codecov
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Publish Package
          command: yarn semantic-release
